// Code generated by "mock-api-gen -type Consul -pkg mockconsul -endpoints event.json -output ./event.go"; DO NOT EDIT.

package mockconsul

import (
	"fmt"
	mockapi "github.com/panhongrainbow/mock-http-api"
)

func (m *Consul) EventFire(event string, body []byte, status int, reply interface{}) *mockapi.MockAPICall {
	req := mockapi.NewMockRequest("PUT", fmt.Sprintf("/v1/event/fire/%s", event)).WithBody(body)

	return m.WithJSONReply(req, status, reply)
}
